// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: msg/msgpb/msg.proto

/*
	Package msgpb is a generated protocol buffer package.

	It is generated from these files:
		msg/msgpb/msg.proto

	It has these top-level messages:
		HandshakeRequest
		HandshakeResponse
		PingRequest
		PingResponse
		TunnelHandshakeRequest
		TunnelHandshakeResponse
		NewTunnelRequest
		NewTunnelResponse
		CloseTunnelRequest
		CloseTunnelResponse
		ShutdownRequest
		Message
*/
package msgpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ErrCode int32

const (
	ErrCodeNull                ErrCode = 0
	ErrCodeBadClient           ErrCode = 1
	ErrCodeBadVersion          ErrCode = 2
	ErrCodeBadProtoOrAddr      ErrCode = 3
	ErrCodeBadRegistryAddr     ErrCode = 4
	ErrCodeNoSuchTunnel        ErrCode = 5
	ErrCodeDuplicateAgent      ErrCode = 6
	ErrCodeInternalServerError ErrCode = 7
)

var ErrCode_name = map[int32]string{
	0: "ErrCodeNull",
	1: "ErrCodeBadClient",
	2: "ErrCodeBadVersion",
	3: "ErrCodeBadProtoOrAddr",
	4: "ErrCodeBadRegistryAddr",
	5: "ErrCodeNoSuchTunnel",
	6: "ErrCodeDuplicateAgent",
	7: "ErrCodeInternalServerError",
}
var ErrCode_value = map[string]int32{
	"ErrCodeNull":                0,
	"ErrCodeBadClient":           1,
	"ErrCodeBadVersion":          2,
	"ErrCodeBadProtoOrAddr":      3,
	"ErrCodeBadRegistryAddr":     4,
	"ErrCodeNoSuchTunnel":        5,
	"ErrCodeDuplicateAgent":      6,
	"ErrCodeInternalServerError": 7,
}

func (x ErrCode) String() string {
	return proto.EnumName(ErrCode_name, int32(x))
}
func (ErrCode) EnumDescriptor() ([]byte, []int) { return fileDescriptorMsg, []int{0} }

// client <-> server
// - control
type HandshakeRequest struct {
	ID      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hash    string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Device  string `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"`
}

func (m *HandshakeRequest) Reset()                    { *m = HandshakeRequest{} }
func (m *HandshakeRequest) String() string            { return proto.CompactTextString(m) }
func (*HandshakeRequest) ProtoMessage()               {}
func (*HandshakeRequest) Descriptor() ([]byte, []int) { return fileDescriptorMsg, []int{0} }

type HandshakeResponse struct {
	ErrCode ErrCode `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3,enum=msgpb.ErrCode" json:"err_code,omitempty"`
}

func (m *HandshakeResponse) Reset()                    { *m = HandshakeResponse{} }
func (m *HandshakeResponse) String() string            { return proto.CompactTextString(m) }
func (*HandshakeResponse) ProtoMessage()               {}
func (*HandshakeResponse) Descriptor() ([]byte, []int) { return fileDescriptorMsg, []int{1} }

type PingRequest struct {
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptorMsg, []int{2} }

type PingResponse struct {
}

func (m *PingResponse) Reset()                    { *m = PingResponse{} }
func (m *PingResponse) String() string            { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()               {}
func (*PingResponse) Descriptor() ([]byte, []int) { return fileDescriptorMsg, []int{3} }

// - exchange data
type TunnelHandshakeRequest struct {
	ID         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientHash string `protobuf:"bytes,2,opt,name=client_hash,json=clientHash,proto3" json:"client_hash,omitempty"`
	TunnelHash string `protobuf:"bytes,3,opt,name=tunnel_hash,json=tunnelHash,proto3" json:"tunnel_hash,omitempty"`
}

func (m *TunnelHandshakeRequest) Reset()                    { *m = TunnelHandshakeRequest{} }
func (m *TunnelHandshakeRequest) String() string            { return proto.CompactTextString(m) }
func (*TunnelHandshakeRequest) ProtoMessage()               {}
func (*TunnelHandshakeRequest) Descriptor() ([]byte, []int) { return fileDescriptorMsg, []int{4} }

type TunnelHandshakeResponse struct {
	ErrCode ErrCode `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3,enum=msgpb.ErrCode" json:"err_code,omitempty"`
}

func (m *TunnelHandshakeResponse) Reset()                    { *m = TunnelHandshakeResponse{} }
func (m *TunnelHandshakeResponse) String() string            { return proto.CompactTextString(m) }
func (*TunnelHandshakeResponse) ProtoMessage()               {}
func (*TunnelHandshakeResponse) Descriptor() ([]byte, []int) { return fileDescriptorMsg, []int{5} }

// server <-> client
type NewTunnelRequest struct {
	ID           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientHash   string `protobuf:"bytes,2,opt,name=client_hash,json=clientHash,proto3" json:"client_hash,omitempty"`
	TunnelHash   string `protobuf:"bytes,3,opt,name=tunnel_hash,json=tunnelHash,proto3" json:"tunnel_hash,omitempty"`
	Proto        string `protobuf:"bytes,4,opt,name=proto,proto3" json:"proto,omitempty"`
	ExportAddr   string `protobuf:"bytes,5,opt,name=export_addr,json=exportAddr,proto3" json:"export_addr,omitempty"`
	RegistryAddr string `protobuf:"bytes,6,opt,name=registry_addr,json=registryAddr,proto3" json:"registry_addr,omitempty"`
}

func (m *NewTunnelRequest) Reset()                    { *m = NewTunnelRequest{} }
func (m *NewTunnelRequest) String() string            { return proto.CompactTextString(m) }
func (*NewTunnelRequest) ProtoMessage()               {}
func (*NewTunnelRequest) Descriptor() ([]byte, []int) { return fileDescriptorMsg, []int{6} }

type NewTunnelResponse struct {
	TunnelHash string  `protobuf:"bytes,1,opt,name=tunnel_hash,json=tunnelHash,proto3" json:"tunnel_hash,omitempty"`
	ErrCode    ErrCode `protobuf:"varint,2,opt,name=err_code,json=errCode,proto3,enum=msgpb.ErrCode" json:"err_code,omitempty"`
}

func (m *NewTunnelResponse) Reset()                    { *m = NewTunnelResponse{} }
func (m *NewTunnelResponse) String() string            { return proto.CompactTextString(m) }
func (*NewTunnelResponse) ProtoMessage()               {}
func (*NewTunnelResponse) Descriptor() ([]byte, []int) { return fileDescriptorMsg, []int{7} }

type CloseTunnelRequest struct {
	ID         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientHash string `protobuf:"bytes,2,opt,name=client_hash,json=clientHash,proto3" json:"client_hash,omitempty"`
	TunnelHash string `protobuf:"bytes,3,opt,name=tunnel_hash,json=tunnelHash,proto3" json:"tunnel_hash,omitempty"`
}

func (m *CloseTunnelRequest) Reset()                    { *m = CloseTunnelRequest{} }
func (m *CloseTunnelRequest) String() string            { return proto.CompactTextString(m) }
func (*CloseTunnelRequest) ProtoMessage()               {}
func (*CloseTunnelRequest) Descriptor() ([]byte, []int) { return fileDescriptorMsg, []int{8} }

type CloseTunnelResponse struct {
	TunnelHash string  `protobuf:"bytes,1,opt,name=tunnel_hash,json=tunnelHash,proto3" json:"tunnel_hash,omitempty"`
	ErrCode    ErrCode `protobuf:"varint,2,opt,name=err_code,json=errCode,proto3,enum=msgpb.ErrCode" json:"err_code,omitempty"`
}

func (m *CloseTunnelResponse) Reset()                    { *m = CloseTunnelResponse{} }
func (m *CloseTunnelResponse) String() string            { return proto.CompactTextString(m) }
func (*CloseTunnelResponse) ProtoMessage()               {}
func (*CloseTunnelResponse) Descriptor() ([]byte, []int) { return fileDescriptorMsg, []int{9} }

type ShutdownRequest struct {
	ID         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientHash string `protobuf:"bytes,2,opt,name=client_hash,json=clientHash,proto3" json:"client_hash,omitempty"`
	TunnelHash string `protobuf:"bytes,3,opt,name=tunnel_hash,json=tunnelHash,proto3" json:"tunnel_hash,omitempty"`
}

func (m *ShutdownRequest) Reset()                    { *m = ShutdownRequest{} }
func (m *ShutdownRequest) String() string            { return proto.CompactTextString(m) }
func (*ShutdownRequest) ProtoMessage()               {}
func (*ShutdownRequest) Descriptor() ([]byte, []int) { return fileDescriptorMsg, []int{10} }

type Message struct {
	// Types that are valid to be assigned to Body:
	//	*Message_HandshakeRequest
	//	*Message_HandshakeResponse
	//	*Message_TunnelHandshakeRequest
	//	*Message_TunnelHandshakeResponse
	//	*Message_PingRequest
	//	*Message_PingResponse
	//	*Message_NewTunnelRequest
	//	*Message_NewTunnelResponse
	//	*Message_CloseTunnelRequest
	//	*Message_CloseTunnelResponse
	//	*Message_ShutdownRequest
	Body isMessage_Body `protobuf_oneof:"body"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptorMsg, []int{11} }

type isMessage_Body interface {
	isMessage_Body()
	MarshalTo([]byte) (int, error)
	Size() int
}

type Message_HandshakeRequest struct {
	HandshakeRequest *HandshakeRequest `protobuf:"bytes,1,opt,name=handshake_request,json=handshakeRequest,oneof"`
}
type Message_HandshakeResponse struct {
	HandshakeResponse *HandshakeResponse `protobuf:"bytes,2,opt,name=handshake_response,json=handshakeResponse,oneof"`
}
type Message_TunnelHandshakeRequest struct {
	TunnelHandshakeRequest *TunnelHandshakeRequest `protobuf:"bytes,3,opt,name=tunnel_handshake_request,json=tunnelHandshakeRequest,oneof"`
}
type Message_TunnelHandshakeResponse struct {
	TunnelHandshakeResponse *TunnelHandshakeResponse `protobuf:"bytes,4,opt,name=tunnel_handshake_response,json=tunnelHandshakeResponse,oneof"`
}
type Message_PingRequest struct {
	PingRequest *PingRequest `protobuf:"bytes,5,opt,name=ping_request,json=pingRequest,oneof"`
}
type Message_PingResponse struct {
	PingResponse *PingResponse `protobuf:"bytes,6,opt,name=ping_response,json=pingResponse,oneof"`
}
type Message_NewTunnelRequest struct {
	NewTunnelRequest *NewTunnelRequest `protobuf:"bytes,7,opt,name=new_tunnel_request,json=newTunnelRequest,oneof"`
}
type Message_NewTunnelResponse struct {
	NewTunnelResponse *NewTunnelResponse `protobuf:"bytes,8,opt,name=new_tunnel_response,json=newTunnelResponse,oneof"`
}
type Message_CloseTunnelRequest struct {
	CloseTunnelRequest *CloseTunnelRequest `protobuf:"bytes,9,opt,name=close_tunnel_request,json=closeTunnelRequest,oneof"`
}
type Message_CloseTunnelResponse struct {
	CloseTunnelResponse *CloseTunnelResponse `protobuf:"bytes,10,opt,name=close_tunnel_response,json=closeTunnelResponse,oneof"`
}
type Message_ShutdownRequest struct {
	ShutdownRequest *ShutdownRequest `protobuf:"bytes,11,opt,name=shutdown_request,json=shutdownRequest,oneof"`
}

func (*Message_HandshakeRequest) isMessage_Body()        {}
func (*Message_HandshakeResponse) isMessage_Body()       {}
func (*Message_TunnelHandshakeRequest) isMessage_Body()  {}
func (*Message_TunnelHandshakeResponse) isMessage_Body() {}
func (*Message_PingRequest) isMessage_Body()             {}
func (*Message_PingResponse) isMessage_Body()            {}
func (*Message_NewTunnelRequest) isMessage_Body()        {}
func (*Message_NewTunnelResponse) isMessage_Body()       {}
func (*Message_CloseTunnelRequest) isMessage_Body()      {}
func (*Message_CloseTunnelResponse) isMessage_Body()     {}
func (*Message_ShutdownRequest) isMessage_Body()         {}

func (m *Message) GetBody() isMessage_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Message) GetHandshakeRequest() *HandshakeRequest {
	if x, ok := m.GetBody().(*Message_HandshakeRequest); ok {
		return x.HandshakeRequest
	}
	return nil
}

func (m *Message) GetHandshakeResponse() *HandshakeResponse {
	if x, ok := m.GetBody().(*Message_HandshakeResponse); ok {
		return x.HandshakeResponse
	}
	return nil
}

func (m *Message) GetTunnelHandshakeRequest() *TunnelHandshakeRequest {
	if x, ok := m.GetBody().(*Message_TunnelHandshakeRequest); ok {
		return x.TunnelHandshakeRequest
	}
	return nil
}

func (m *Message) GetTunnelHandshakeResponse() *TunnelHandshakeResponse {
	if x, ok := m.GetBody().(*Message_TunnelHandshakeResponse); ok {
		return x.TunnelHandshakeResponse
	}
	return nil
}

func (m *Message) GetPingRequest() *PingRequest {
	if x, ok := m.GetBody().(*Message_PingRequest); ok {
		return x.PingRequest
	}
	return nil
}

func (m *Message) GetPingResponse() *PingResponse {
	if x, ok := m.GetBody().(*Message_PingResponse); ok {
		return x.PingResponse
	}
	return nil
}

func (m *Message) GetNewTunnelRequest() *NewTunnelRequest {
	if x, ok := m.GetBody().(*Message_NewTunnelRequest); ok {
		return x.NewTunnelRequest
	}
	return nil
}

func (m *Message) GetNewTunnelResponse() *NewTunnelResponse {
	if x, ok := m.GetBody().(*Message_NewTunnelResponse); ok {
		return x.NewTunnelResponse
	}
	return nil
}

func (m *Message) GetCloseTunnelRequest() *CloseTunnelRequest {
	if x, ok := m.GetBody().(*Message_CloseTunnelRequest); ok {
		return x.CloseTunnelRequest
	}
	return nil
}

func (m *Message) GetCloseTunnelResponse() *CloseTunnelResponse {
	if x, ok := m.GetBody().(*Message_CloseTunnelResponse); ok {
		return x.CloseTunnelResponse
	}
	return nil
}

func (m *Message) GetShutdownRequest() *ShutdownRequest {
	if x, ok := m.GetBody().(*Message_ShutdownRequest); ok {
		return x.ShutdownRequest
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Message) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Message_OneofMarshaler, _Message_OneofUnmarshaler, _Message_OneofSizer, []interface{}{
		(*Message_HandshakeRequest)(nil),
		(*Message_HandshakeResponse)(nil),
		(*Message_TunnelHandshakeRequest)(nil),
		(*Message_TunnelHandshakeResponse)(nil),
		(*Message_PingRequest)(nil),
		(*Message_PingResponse)(nil),
		(*Message_NewTunnelRequest)(nil),
		(*Message_NewTunnelResponse)(nil),
		(*Message_CloseTunnelRequest)(nil),
		(*Message_CloseTunnelResponse)(nil),
		(*Message_ShutdownRequest)(nil),
	}
}

func _Message_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Message)
	// body
	switch x := m.Body.(type) {
	case *Message_HandshakeRequest:
		_ = b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.HandshakeRequest); err != nil {
			return err
		}
	case *Message_HandshakeResponse:
		_ = b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.HandshakeResponse); err != nil {
			return err
		}
	case *Message_TunnelHandshakeRequest:
		_ = b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TunnelHandshakeRequest); err != nil {
			return err
		}
	case *Message_TunnelHandshakeResponse:
		_ = b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TunnelHandshakeResponse); err != nil {
			return err
		}
	case *Message_PingRequest:
		_ = b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PingRequest); err != nil {
			return err
		}
	case *Message_PingResponse:
		_ = b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PingResponse); err != nil {
			return err
		}
	case *Message_NewTunnelRequest:
		_ = b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.NewTunnelRequest); err != nil {
			return err
		}
	case *Message_NewTunnelResponse:
		_ = b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.NewTunnelResponse); err != nil {
			return err
		}
	case *Message_CloseTunnelRequest:
		_ = b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CloseTunnelRequest); err != nil {
			return err
		}
	case *Message_CloseTunnelResponse:
		_ = b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CloseTunnelResponse); err != nil {
			return err
		}
	case *Message_ShutdownRequest:
		_ = b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ShutdownRequest); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Message.Body has unexpected type %T", x)
	}
	return nil
}

func _Message_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Message)
	switch tag {
	case 1: // body.handshake_request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HandshakeRequest)
		err := b.DecodeMessage(msg)
		m.Body = &Message_HandshakeRequest{msg}
		return true, err
	case 2: // body.handshake_response
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HandshakeResponse)
		err := b.DecodeMessage(msg)
		m.Body = &Message_HandshakeResponse{msg}
		return true, err
	case 3: // body.tunnel_handshake_request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TunnelHandshakeRequest)
		err := b.DecodeMessage(msg)
		m.Body = &Message_TunnelHandshakeRequest{msg}
		return true, err
	case 4: // body.tunnel_handshake_response
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TunnelHandshakeResponse)
		err := b.DecodeMessage(msg)
		m.Body = &Message_TunnelHandshakeResponse{msg}
		return true, err
	case 5: // body.ping_request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PingRequest)
		err := b.DecodeMessage(msg)
		m.Body = &Message_PingRequest{msg}
		return true, err
	case 6: // body.ping_response
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PingResponse)
		err := b.DecodeMessage(msg)
		m.Body = &Message_PingResponse{msg}
		return true, err
	case 7: // body.new_tunnel_request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(NewTunnelRequest)
		err := b.DecodeMessage(msg)
		m.Body = &Message_NewTunnelRequest{msg}
		return true, err
	case 8: // body.new_tunnel_response
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(NewTunnelResponse)
		err := b.DecodeMessage(msg)
		m.Body = &Message_NewTunnelResponse{msg}
		return true, err
	case 9: // body.close_tunnel_request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CloseTunnelRequest)
		err := b.DecodeMessage(msg)
		m.Body = &Message_CloseTunnelRequest{msg}
		return true, err
	case 10: // body.close_tunnel_response
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CloseTunnelResponse)
		err := b.DecodeMessage(msg)
		m.Body = &Message_CloseTunnelResponse{msg}
		return true, err
	case 11: // body.shutdown_request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ShutdownRequest)
		err := b.DecodeMessage(msg)
		m.Body = &Message_ShutdownRequest{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Message_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Message)
	// body
	switch x := m.Body.(type) {
	case *Message_HandshakeRequest:
		s := proto.Size(x.HandshakeRequest)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_HandshakeResponse:
		s := proto.Size(x.HandshakeResponse)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_TunnelHandshakeRequest:
		s := proto.Size(x.TunnelHandshakeRequest)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_TunnelHandshakeResponse:
		s := proto.Size(x.TunnelHandshakeResponse)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_PingRequest:
		s := proto.Size(x.PingRequest)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_PingResponse:
		s := proto.Size(x.PingResponse)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_NewTunnelRequest:
		s := proto.Size(x.NewTunnelRequest)
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_NewTunnelResponse:
		s := proto.Size(x.NewTunnelResponse)
		n += proto.SizeVarint(8<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_CloseTunnelRequest:
		s := proto.Size(x.CloseTunnelRequest)
		n += proto.SizeVarint(9<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_CloseTunnelResponse:
		s := proto.Size(x.CloseTunnelResponse)
		n += proto.SizeVarint(10<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_ShutdownRequest:
		s := proto.Size(x.ShutdownRequest)
		n += proto.SizeVarint(11<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*HandshakeRequest)(nil), "msgpb.HandshakeRequest")
	proto.RegisterType((*HandshakeResponse)(nil), "msgpb.HandshakeResponse")
	proto.RegisterType((*PingRequest)(nil), "msgpb.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "msgpb.PingResponse")
	proto.RegisterType((*TunnelHandshakeRequest)(nil), "msgpb.TunnelHandshakeRequest")
	proto.RegisterType((*TunnelHandshakeResponse)(nil), "msgpb.TunnelHandshakeResponse")
	proto.RegisterType((*NewTunnelRequest)(nil), "msgpb.NewTunnelRequest")
	proto.RegisterType((*NewTunnelResponse)(nil), "msgpb.NewTunnelResponse")
	proto.RegisterType((*CloseTunnelRequest)(nil), "msgpb.CloseTunnelRequest")
	proto.RegisterType((*CloseTunnelResponse)(nil), "msgpb.CloseTunnelResponse")
	proto.RegisterType((*ShutdownRequest)(nil), "msgpb.ShutdownRequest")
	proto.RegisterType((*Message)(nil), "msgpb.Message")
	proto.RegisterEnum("msgpb.ErrCode", ErrCode_name, ErrCode_value)
}
func (m *HandshakeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HandshakeRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintMsg(dAtA, i, uint64(len(m.ID)))
		i += copy(dAtA[i:], m.ID)
	}
	if len(m.Hash) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintMsg(dAtA, i, uint64(len(m.Hash)))
		i += copy(dAtA[i:], m.Hash)
	}
	if len(m.Version) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintMsg(dAtA, i, uint64(len(m.Version)))
		i += copy(dAtA[i:], m.Version)
	}
	if len(m.Device) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintMsg(dAtA, i, uint64(len(m.Device)))
		i += copy(dAtA[i:], m.Device)
	}
	return i, nil
}

func (m *HandshakeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HandshakeResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ErrCode != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintMsg(dAtA, i, uint64(m.ErrCode))
	}
	return i, nil
}

func (m *PingRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PingRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *PingResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PingResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *TunnelHandshakeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TunnelHandshakeRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintMsg(dAtA, i, uint64(len(m.ID)))
		i += copy(dAtA[i:], m.ID)
	}
	if len(m.ClientHash) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintMsg(dAtA, i, uint64(len(m.ClientHash)))
		i += copy(dAtA[i:], m.ClientHash)
	}
	if len(m.TunnelHash) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintMsg(dAtA, i, uint64(len(m.TunnelHash)))
		i += copy(dAtA[i:], m.TunnelHash)
	}
	return i, nil
}

func (m *TunnelHandshakeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TunnelHandshakeResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ErrCode != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintMsg(dAtA, i, uint64(m.ErrCode))
	}
	return i, nil
}

func (m *NewTunnelRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NewTunnelRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintMsg(dAtA, i, uint64(len(m.ID)))
		i += copy(dAtA[i:], m.ID)
	}
	if len(m.ClientHash) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintMsg(dAtA, i, uint64(len(m.ClientHash)))
		i += copy(dAtA[i:], m.ClientHash)
	}
	if len(m.TunnelHash) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintMsg(dAtA, i, uint64(len(m.TunnelHash)))
		i += copy(dAtA[i:], m.TunnelHash)
	}
	if len(m.Proto) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintMsg(dAtA, i, uint64(len(m.Proto)))
		i += copy(dAtA[i:], m.Proto)
	}
	if len(m.ExportAddr) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintMsg(dAtA, i, uint64(len(m.ExportAddr)))
		i += copy(dAtA[i:], m.ExportAddr)
	}
	if len(m.RegistryAddr) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintMsg(dAtA, i, uint64(len(m.RegistryAddr)))
		i += copy(dAtA[i:], m.RegistryAddr)
	}
	return i, nil
}

func (m *NewTunnelResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NewTunnelResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.TunnelHash) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintMsg(dAtA, i, uint64(len(m.TunnelHash)))
		i += copy(dAtA[i:], m.TunnelHash)
	}
	if m.ErrCode != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintMsg(dAtA, i, uint64(m.ErrCode))
	}
	return i, nil
}

func (m *CloseTunnelRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CloseTunnelRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintMsg(dAtA, i, uint64(len(m.ID)))
		i += copy(dAtA[i:], m.ID)
	}
	if len(m.ClientHash) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintMsg(dAtA, i, uint64(len(m.ClientHash)))
		i += copy(dAtA[i:], m.ClientHash)
	}
	if len(m.TunnelHash) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintMsg(dAtA, i, uint64(len(m.TunnelHash)))
		i += copy(dAtA[i:], m.TunnelHash)
	}
	return i, nil
}

func (m *CloseTunnelResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CloseTunnelResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.TunnelHash) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintMsg(dAtA, i, uint64(len(m.TunnelHash)))
		i += copy(dAtA[i:], m.TunnelHash)
	}
	if m.ErrCode != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintMsg(dAtA, i, uint64(m.ErrCode))
	}
	return i, nil
}

func (m *ShutdownRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ShutdownRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintMsg(dAtA, i, uint64(len(m.ID)))
		i += copy(dAtA[i:], m.ID)
	}
	if len(m.ClientHash) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintMsg(dAtA, i, uint64(len(m.ClientHash)))
		i += copy(dAtA[i:], m.ClientHash)
	}
	if len(m.TunnelHash) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintMsg(dAtA, i, uint64(len(m.TunnelHash)))
		i += copy(dAtA[i:], m.TunnelHash)
	}
	return i, nil
}

func (m *Message) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Message) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Body != nil {
		nn1, err := m.Body.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += nn1
	}
	return i, nil
}

func (m *Message_HandshakeRequest) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.HandshakeRequest != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintMsg(dAtA, i, uint64(m.HandshakeRequest.Size()))
		n2, err := m.HandshakeRequest.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	return i, nil
}
func (m *Message_HandshakeResponse) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.HandshakeResponse != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintMsg(dAtA, i, uint64(m.HandshakeResponse.Size()))
		n3, err := m.HandshakeResponse.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	return i, nil
}
func (m *Message_TunnelHandshakeRequest) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.TunnelHandshakeRequest != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintMsg(dAtA, i, uint64(m.TunnelHandshakeRequest.Size()))
		n4, err := m.TunnelHandshakeRequest.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n4
	}
	return i, nil
}
func (m *Message_TunnelHandshakeResponse) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.TunnelHandshakeResponse != nil {
		dAtA[i] = 0x22
		i++
		i = encodeVarintMsg(dAtA, i, uint64(m.TunnelHandshakeResponse.Size()))
		n5, err := m.TunnelHandshakeResponse.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n5
	}
	return i, nil
}
func (m *Message_PingRequest) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.PingRequest != nil {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintMsg(dAtA, i, uint64(m.PingRequest.Size()))
		n6, err := m.PingRequest.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n6
	}
	return i, nil
}
func (m *Message_PingResponse) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.PingResponse != nil {
		dAtA[i] = 0x32
		i++
		i = encodeVarintMsg(dAtA, i, uint64(m.PingResponse.Size()))
		n7, err := m.PingResponse.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n7
	}
	return i, nil
}
func (m *Message_NewTunnelRequest) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.NewTunnelRequest != nil {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintMsg(dAtA, i, uint64(m.NewTunnelRequest.Size()))
		n8, err := m.NewTunnelRequest.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n8
	}
	return i, nil
}
func (m *Message_NewTunnelResponse) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.NewTunnelResponse != nil {
		dAtA[i] = 0x42
		i++
		i = encodeVarintMsg(dAtA, i, uint64(m.NewTunnelResponse.Size()))
		n9, err := m.NewTunnelResponse.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n9
	}
	return i, nil
}
func (m *Message_CloseTunnelRequest) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.CloseTunnelRequest != nil {
		dAtA[i] = 0x4a
		i++
		i = encodeVarintMsg(dAtA, i, uint64(m.CloseTunnelRequest.Size()))
		n10, err := m.CloseTunnelRequest.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n10
	}
	return i, nil
}
func (m *Message_CloseTunnelResponse) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.CloseTunnelResponse != nil {
		dAtA[i] = 0x52
		i++
		i = encodeVarintMsg(dAtA, i, uint64(m.CloseTunnelResponse.Size()))
		n11, err := m.CloseTunnelResponse.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n11
	}
	return i, nil
}
func (m *Message_ShutdownRequest) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.ShutdownRequest != nil {
		dAtA[i] = 0x5a
		i++
		i = encodeVarintMsg(dAtA, i, uint64(m.ShutdownRequest.Size()))
		n12, err := m.ShutdownRequest.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n12
	}
	return i, nil
}
func encodeFixed64Msg(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Msg(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintMsg(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *HandshakeRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovMsg(uint64(l))
	}
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovMsg(uint64(l))
	}
	l = len(m.Version)
	if l > 0 {
		n += 1 + l + sovMsg(uint64(l))
	}
	l = len(m.Device)
	if l > 0 {
		n += 1 + l + sovMsg(uint64(l))
	}
	return n
}

func (m *HandshakeResponse) Size() (n int) {
	var l int
	_ = l
	if m.ErrCode != 0 {
		n += 1 + sovMsg(uint64(m.ErrCode))
	}
	return n
}

func (m *PingRequest) Size() (n int) {
	var l int
	_ = l
	return n
}

func (m *PingResponse) Size() (n int) {
	var l int
	_ = l
	return n
}

func (m *TunnelHandshakeRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovMsg(uint64(l))
	}
	l = len(m.ClientHash)
	if l > 0 {
		n += 1 + l + sovMsg(uint64(l))
	}
	l = len(m.TunnelHash)
	if l > 0 {
		n += 1 + l + sovMsg(uint64(l))
	}
	return n
}

func (m *TunnelHandshakeResponse) Size() (n int) {
	var l int
	_ = l
	if m.ErrCode != 0 {
		n += 1 + sovMsg(uint64(m.ErrCode))
	}
	return n
}

func (m *NewTunnelRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovMsg(uint64(l))
	}
	l = len(m.ClientHash)
	if l > 0 {
		n += 1 + l + sovMsg(uint64(l))
	}
	l = len(m.TunnelHash)
	if l > 0 {
		n += 1 + l + sovMsg(uint64(l))
	}
	l = len(m.Proto)
	if l > 0 {
		n += 1 + l + sovMsg(uint64(l))
	}
	l = len(m.ExportAddr)
	if l > 0 {
		n += 1 + l + sovMsg(uint64(l))
	}
	l = len(m.RegistryAddr)
	if l > 0 {
		n += 1 + l + sovMsg(uint64(l))
	}
	return n
}

func (m *NewTunnelResponse) Size() (n int) {
	var l int
	_ = l
	l = len(m.TunnelHash)
	if l > 0 {
		n += 1 + l + sovMsg(uint64(l))
	}
	if m.ErrCode != 0 {
		n += 1 + sovMsg(uint64(m.ErrCode))
	}
	return n
}

func (m *CloseTunnelRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovMsg(uint64(l))
	}
	l = len(m.ClientHash)
	if l > 0 {
		n += 1 + l + sovMsg(uint64(l))
	}
	l = len(m.TunnelHash)
	if l > 0 {
		n += 1 + l + sovMsg(uint64(l))
	}
	return n
}

func (m *CloseTunnelResponse) Size() (n int) {
	var l int
	_ = l
	l = len(m.TunnelHash)
	if l > 0 {
		n += 1 + l + sovMsg(uint64(l))
	}
	if m.ErrCode != 0 {
		n += 1 + sovMsg(uint64(m.ErrCode))
	}
	return n
}

func (m *ShutdownRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovMsg(uint64(l))
	}
	l = len(m.ClientHash)
	if l > 0 {
		n += 1 + l + sovMsg(uint64(l))
	}
	l = len(m.TunnelHash)
	if l > 0 {
		n += 1 + l + sovMsg(uint64(l))
	}
	return n
}

func (m *Message) Size() (n int) {
	var l int
	_ = l
	if m.Body != nil {
		n += m.Body.Size()
	}
	return n
}

func (m *Message_HandshakeRequest) Size() (n int) {
	var l int
	_ = l
	if m.HandshakeRequest != nil {
		l = m.HandshakeRequest.Size()
		n += 1 + l + sovMsg(uint64(l))
	}
	return n
}
func (m *Message_HandshakeResponse) Size() (n int) {
	var l int
	_ = l
	if m.HandshakeResponse != nil {
		l = m.HandshakeResponse.Size()
		n += 1 + l + sovMsg(uint64(l))
	}
	return n
}
func (m *Message_TunnelHandshakeRequest) Size() (n int) {
	var l int
	_ = l
	if m.TunnelHandshakeRequest != nil {
		l = m.TunnelHandshakeRequest.Size()
		n += 1 + l + sovMsg(uint64(l))
	}
	return n
}
func (m *Message_TunnelHandshakeResponse) Size() (n int) {
	var l int
	_ = l
	if m.TunnelHandshakeResponse != nil {
		l = m.TunnelHandshakeResponse.Size()
		n += 1 + l + sovMsg(uint64(l))
	}
	return n
}
func (m *Message_PingRequest) Size() (n int) {
	var l int
	_ = l
	if m.PingRequest != nil {
		l = m.PingRequest.Size()
		n += 1 + l + sovMsg(uint64(l))
	}
	return n
}
func (m *Message_PingResponse) Size() (n int) {
	var l int
	_ = l
	if m.PingResponse != nil {
		l = m.PingResponse.Size()
		n += 1 + l + sovMsg(uint64(l))
	}
	return n
}
func (m *Message_NewTunnelRequest) Size() (n int) {
	var l int
	_ = l
	if m.NewTunnelRequest != nil {
		l = m.NewTunnelRequest.Size()
		n += 1 + l + sovMsg(uint64(l))
	}
	return n
}
func (m *Message_NewTunnelResponse) Size() (n int) {
	var l int
	_ = l
	if m.NewTunnelResponse != nil {
		l = m.NewTunnelResponse.Size()
		n += 1 + l + sovMsg(uint64(l))
	}
	return n
}
func (m *Message_CloseTunnelRequest) Size() (n int) {
	var l int
	_ = l
	if m.CloseTunnelRequest != nil {
		l = m.CloseTunnelRequest.Size()
		n += 1 + l + sovMsg(uint64(l))
	}
	return n
}
func (m *Message_CloseTunnelResponse) Size() (n int) {
	var l int
	_ = l
	if m.CloseTunnelResponse != nil {
		l = m.CloseTunnelResponse.Size()
		n += 1 + l + sovMsg(uint64(l))
	}
	return n
}
func (m *Message_ShutdownRequest) Size() (n int) {
	var l int
	_ = l
	if m.ShutdownRequest != nil {
		l = m.ShutdownRequest.Size()
		n += 1 + l + sovMsg(uint64(l))
	}
	return n
}

func sovMsg(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozMsg(x uint64) (n int) {
	return sovMsg(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *HandshakeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HandshakeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HandshakeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Version = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Device", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Device = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HandshakeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HandshakeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HandshakeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrCode", wireType)
			}
			m.ErrCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ErrCode |= (ErrCode(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PingRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PingRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PingRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipMsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PingResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PingResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PingResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipMsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TunnelHandshakeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TunnelHandshakeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TunnelHandshakeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TunnelHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TunnelHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TunnelHandshakeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TunnelHandshakeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TunnelHandshakeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrCode", wireType)
			}
			m.ErrCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ErrCode |= (ErrCode(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NewTunnelRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NewTunnelRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NewTunnelRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TunnelHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TunnelHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proto", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proto = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExportAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExportAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegistryAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegistryAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NewTunnelResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NewTunnelResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NewTunnelResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TunnelHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TunnelHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrCode", wireType)
			}
			m.ErrCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ErrCode |= (ErrCode(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CloseTunnelRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CloseTunnelRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CloseTunnelRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TunnelHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TunnelHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CloseTunnelResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CloseTunnelResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CloseTunnelResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TunnelHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TunnelHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrCode", wireType)
			}
			m.ErrCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ErrCode |= (ErrCode(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ShutdownRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ShutdownRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ShutdownRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TunnelHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TunnelHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Message) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Message: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Message: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HandshakeRequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &HandshakeRequest{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Body = &Message_HandshakeRequest{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HandshakeResponse", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &HandshakeResponse{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Body = &Message_HandshakeResponse{v}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TunnelHandshakeRequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &TunnelHandshakeRequest{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Body = &Message_TunnelHandshakeRequest{v}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TunnelHandshakeResponse", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &TunnelHandshakeResponse{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Body = &Message_TunnelHandshakeResponse{v}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PingRequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &PingRequest{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Body = &Message_PingRequest{v}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PingResponse", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &PingResponse{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Body = &Message_PingResponse{v}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewTunnelRequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &NewTunnelRequest{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Body = &Message_NewTunnelRequest{v}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewTunnelResponse", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &NewTunnelResponse{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Body = &Message_NewTunnelResponse{v}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CloseTunnelRequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &CloseTunnelRequest{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Body = &Message_CloseTunnelRequest{v}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CloseTunnelResponse", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &CloseTunnelResponse{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Body = &Message_CloseTunnelResponse{v}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShutdownRequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsg
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &ShutdownRequest{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Body = &Message_ShutdownRequest{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsg(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsg
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsg
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthMsg
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowMsg
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipMsg(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthMsg = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsg   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("msg/msgpb/msg.proto", fileDescriptorMsg) }

var fileDescriptorMsg = []byte{
	// 785 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xd1, 0x4e, 0xdb, 0x48,
	0x14, 0xb5, 0x43, 0xe2, 0xc0, 0x75, 0x00, 0x67, 0x02, 0x89, 0x89, 0xb4, 0x66, 0xe5, 0x7d, 0xd9,
	0x5d, 0x69, 0x83, 0xc4, 0x3e, 0xac, 0xb4, 0x0f, 0x95, 0x48, 0xa0, 0x35, 0x95, 0xa0, 0xc8, 0x54,
	0x95, 0x2a, 0x55, 0x8a, 0x1c, 0x7b, 0x6a, 0x5b, 0x04, 0xdb, 0x1d, 0xdb, 0x50, 0xfe, 0xa4, 0x9f,
	0xc4, 0x4b, 0x25, 0xd4, 0x0f, 0xa8, 0x4a, 0xfa, 0x23, 0x95, 0x67, 0x26, 0x89, 0x63, 0x87, 0xaa,
	0x7d, 0xa0, 0x2f, 0xd1, 0xdc, 0x3b, 0x73, 0xcf, 0x3d, 0x67, 0x26, 0xe7, 0x1a, 0x5a, 0x97, 0xb1,
	0xbb, 0x77, 0x19, 0xbb, 0xd1, 0x28, 0xfb, 0xed, 0x45, 0x24, 0x4c, 0x42, 0x54, 0xa3, 0x89, 0xee,
	0x3f, 0xae, 0x9f, 0x78, 0xe9, 0xa8, 0x67, 0x87, 0x97, 0x7b, 0x6e, 0xe8, 0x86, 0x7b, 0x74, 0x77,
	0x94, 0xbe, 0xa5, 0x11, 0x0d, 0xe8, 0x8a, 0x55, 0xe9, 0x11, 0x28, 0x86, 0x15, 0x38, 0xb1, 0x67,
	0x5d, 0x60, 0x13, 0xbf, 0x4b, 0x71, 0x9c, 0xa0, 0x36, 0x54, 0x7c, 0x47, 0x15, 0x7f, 0x17, 0xff,
	0x5c, 0xeb, 0x4b, 0x93, 0xcf, 0xbb, 0x95, 0xe3, 0x43, 0xb3, 0xe2, 0x3b, 0x08, 0x41, 0xd5, 0xb3,
	0x62, 0x4f, 0xad, 0x64, 0x3b, 0x26, 0x5d, 0x23, 0x15, 0xea, 0x57, 0x98, 0xc4, 0x7e, 0x18, 0xa8,
	0x2b, 0x34, 0x3d, 0x0d, 0x51, 0x1b, 0x24, 0x07, 0x5f, 0xf9, 0x36, 0x56, 0xab, 0x74, 0x83, 0x47,
	0xfa, 0x13, 0x68, 0xe6, 0x3a, 0xc6, 0x51, 0x18, 0xc4, 0x18, 0xfd, 0x05, 0xab, 0x98, 0x90, 0xa1,
	0x1d, 0x3a, 0x98, 0x36, 0xde, 0xd8, 0xdf, 0xe8, 0x51, 0x3d, 0xbd, 0x23, 0x42, 0x06, 0xa1, 0x83,
	0xcd, 0x3a, 0x66, 0x0b, 0x7d, 0x1d, 0xe4, 0x33, 0x3f, 0x70, 0x39, 0x59, 0x7d, 0x03, 0x1a, 0x2c,
	0x64, 0x48, 0x3a, 0x81, 0xf6, 0xcb, 0x34, 0x08, 0xf0, 0xf8, 0x87, 0x65, 0xed, 0x82, 0x6c, 0x8f,
	0x7d, 0x1c, 0x24, 0xc3, 0x9c, 0x3a, 0x60, 0x29, 0x23, 0xd3, 0xb8, 0x0b, 0x72, 0x42, 0x21, 0xd9,
	0x01, 0xa6, 0x13, 0x12, 0xde, 0x25, 0xf6, 0xf4, 0x43, 0xe8, 0x94, 0x7a, 0xfe, 0xbc, 0xb0, 0x5b,
	0x11, 0x94, 0x53, 0x7c, 0xcd, 0x90, 0x1e, 0x9d, 0x34, 0xda, 0x82, 0x1a, 0xfd, 0x0b, 0xf0, 0xe7,
	0x61, 0x41, 0x56, 0x86, 0xdf, 0x47, 0x21, 0x49, 0x86, 0x96, 0xe3, 0x10, 0xb5, 0xc6, 0xca, 0x58,
	0xea, 0xc0, 0x71, 0x08, 0xfa, 0x03, 0xd6, 0x09, 0x76, 0xfd, 0x38, 0x21, 0x37, 0xec, 0x88, 0x44,
	0x8f, 0x34, 0xa6, 0xc9, 0xec, 0x90, 0x3e, 0x84, 0x66, 0x4e, 0x09, 0xbf, 0x8a, 0x02, 0x23, 0xb1,
	0xc4, 0x28, 0x7f, 0x57, 0x95, 0xef, 0xdf, 0x55, 0x00, 0x68, 0x30, 0x0e, 0x63, 0xfc, 0x8b, 0x2e,
	0x4b, 0xb7, 0xa0, 0xb5, 0xd0, 0xef, 0x11, 0x24, 0x5d, 0xc0, 0xe6, 0xb9, 0x97, 0x26, 0x4e, 0x78,
	0x1d, 0x3c, 0xbe, 0x9e, 0x8f, 0x12, 0xd4, 0x4f, 0x70, 0x1c, 0x5b, 0x2e, 0x46, 0x4f, 0xa1, 0xe9,
	0x4d, 0xff, 0xb7, 0x43, 0xc2, 0x5a, 0xd3, 0xa6, 0xf2, 0x7e, 0x87, 0x93, 0x2d, 0x7a, 0xc9, 0x10,
	0x4c, 0xc5, 0x2b, 0xfa, 0xeb, 0x18, 0x50, 0x1e, 0x87, 0x5d, 0x11, 0x25, 0x27, 0xef, 0xab, 0x65,
	0x20, 0xb6, 0x6f, 0x08, 0x66, 0xd3, 0x2b, 0xb9, 0xe6, 0x35, 0xa8, 0x33, 0xfe, 0x45, 0x66, 0x2b,
	0x14, 0xf0, 0x37, 0x0e, 0xb8, 0xdc, 0xeb, 0x86, 0x60, 0xb6, 0x93, 0xe5, 0x53, 0xe0, 0x0d, 0xec,
	0x2c, 0x81, 0xe6, 0x64, 0xab, 0x14, 0x5b, 0x7b, 0x08, 0x7b, 0x46, 0xb9, 0x93, 0x3c, 0x60, 0xf7,
	0xff, 0xa0, 0x11, 0xf9, 0x81, 0x3b, 0x23, 0x5b, 0xa3, 0x80, 0x88, 0x03, 0xe6, 0xe6, 0x96, 0x21,
	0x98, 0x72, 0x34, 0x0f, 0xd1, 0xff, 0xb0, 0xce, 0x0b, 0x39, 0x15, 0x89, 0x56, 0xb6, 0x16, 0x2a,
	0x67, 0xfd, 0x1b, 0x51, 0x2e, 0x46, 0xcf, 0x00, 0x05, 0xf8, 0x7a, 0xc8, 0x65, 0x4d, 0x5b, 0xd7,
	0x17, 0x5e, 0xb0, 0x38, 0x58, 0xb2, 0x17, 0x0c, 0x8a, 0xc3, 0xe6, 0x39, 0xb4, 0x16, 0x80, 0x38,
	0x95, 0xd5, 0x85, 0x27, 0x2c, 0x19, 0x3b, 0x7b, 0xc2, 0xa0, 0xe4, 0xf6, 0x13, 0xd8, 0xb2, 0x33,
	0xc7, 0x14, 0x69, 0xad, 0x51, 0xb0, 0x1d, 0x0e, 0x56, 0x36, 0xb1, 0x21, 0x98, 0xc8, 0x2e, 0x5b,
	0xfb, 0x0c, 0xb6, 0x0b, 0x70, 0x9c, 0x1c, 0x50, 0xbc, 0xee, 0x32, 0xbc, 0x19, 0xbd, 0x96, 0xbd,
	0xc4, 0xbb, 0x03, 0x50, 0x62, 0xee, 0xb7, 0x19, 0x39, 0x99, 0x82, 0xb5, 0x39, 0x58, 0xc1, 0x8e,
	0x86, 0x60, 0x6e, 0xc6, 0x8b, 0xa9, 0xbe, 0x04, 0xd5, 0x51, 0xe8, 0xdc, 0xfc, 0xfd, 0x49, 0x84,
	0x3a, 0x77, 0x34, 0xda, 0x04, 0x99, 0x2f, 0x4f, 0xd3, 0xf1, 0x58, 0x11, 0xd0, 0x16, 0x28, 0x3c,
	0xd1, 0xb7, 0x9c, 0x01, 0x75, 0xa9, 0x22, 0xa2, 0x6d, 0x68, 0xce, 0xb3, 0xaf, 0xd8, 0x47, 0x53,
	0xa9, 0xa0, 0x1d, 0xd8, 0x9e, 0xa7, 0xcf, 0xb2, 0x99, 0xfc, 0x82, 0x64, 0x33, 0x55, 0x59, 0x41,
	0x5d, 0x68, 0xcf, 0xb7, 0xcc, 0xdc, 0xbc, 0x55, 0xaa, 0xa8, 0x03, 0xad, 0x69, 0xd3, 0xf0, 0x3c,
	0xb5, 0x3d, 0x26, 0x56, 0xa9, 0xe5, 0xf0, 0x0e, 0xd3, 0x68, 0xec, 0xdb, 0x56, 0x82, 0x0f, 0xdc,
	0x8c, 0x81, 0x84, 0x34, 0xe8, 0xf2, 0xad, 0xe3, 0x20, 0xc1, 0x24, 0xb0, 0xc6, 0xe7, 0x98, 0x5c,
	0x61, 0x72, 0x44, 0x48, 0x48, 0x94, 0x7a, 0x5f, 0xbd, 0xbd, 0xd7, 0x84, 0xbb, 0x7b, 0x4d, 0xb8,
	0x9d, 0x68, 0xe2, 0xdd, 0x44, 0x13, 0xbf, 0x4c, 0x34, 0xf1, 0xc3, 0x57, 0x4d, 0x18, 0x49, 0xf4,
	0x63, 0xf1, 0xef, 0xb7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9d, 0x9d, 0x46, 0xd1, 0x89, 0x08, 0x00,
	0x00,
}
